USE [master]
GO

/****** Object:  Database [Walkabout]    Script Date: 22-08-2022 13:53:04 ******/
CREATE DATABASE [Walkabout]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Walkabout', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Walkabout.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Walkabout_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Walkabout_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Walkabout].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Walkabout] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Walkabout] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Walkabout] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Walkabout] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Walkabout] SET ARITHABORT OFF 
GO

ALTER DATABASE [Walkabout] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Walkabout] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Walkabout] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Walkabout] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Walkabout] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Walkabout] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Walkabout] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Walkabout] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Walkabout] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Walkabout] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Walkabout] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Walkabout] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Walkabout] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Walkabout] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Walkabout] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Walkabout] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Walkabout] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Walkabout] SET RECOVERY FULL 
GO

ALTER DATABASE [Walkabout] SET  MULTI_USER 
GO

ALTER DATABASE [Walkabout] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Walkabout] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Walkabout] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Walkabout] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Walkabout] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Walkabout] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Walkabout] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Walkabout] SET  READ_WRITE 
GO

